create or replace TABLE STG_DB_INDIA.OMS_AGG_INTERMEDIATE.COMPLETED_SPOT_ORDERS_FOR_LTO_LTV_SOURCES (
	ID NUMBER(38,0) NOT NULL,
	CUSTOMER_ID NUMBER(38,0),
	VEHICLE_ID NUMBER(38,0),
	GEO_REGION_ID NUMBER(38,0),
	CUSTOMER_FARE_WITHOUT_PREVIOUS_DUE NUMBER(38,15),
	ORDER_DATE DATE,
	UPDATED_AT TIMESTAMP_NTZ(9),
	_ETL_BATCH_ID VARCHAR(16777216),
	_ETL_INSERT_DATE_TIME TIMESTAMP_NTZ(9),
	_ETL_UPDATE_DATE_TIME TIMESTAMP_NTZ(9)
);
