create or replace TABLE RAW_DB_INDIA.SFMS_PUBLIC.SF_ACCOUNT_HISTORIES (
	RAW_DATA VARIANT,
	_ETL_BATCH_ID VARCHAR(16777216),
	_ETL_INSERT_DATE_TIME TIMESTAMP_NTZ(9),
	_ETL_UPDATE_DATE_TIME TIMESTAMP_NTZ(9)
);
