create or replace TABLE CURATED_DB_INDIA.COMMONS_CRM.BANNERS (
	ID NUMBER(38,0) NOT NULL,
	IMAGE_URL VARCHAR(16777216) NOT NULL,
	LANDING_URL VARCHAR(16777216),
	CREATED_AT TIMESTAMP_TZ(9) NOT NULL,
	UPDATED_AT TIMESTAMP_TZ(9) NOT NULL,
	PRIORITY NUMBER(38,0) NOT NULL,
	STATUS VARCHAR(16777216) NOT NULL,
	_ETL_BATCH_ID VARCHAR(16777216),
	_ETL_INSERT_DATE_TIME TIMESTAMP_NTZ(9),
	_ETL_UPDATE_DATE_TIME TIMESTAMP_NTZ(9)
);
