create or replace TABLE CURATED_DB_INDIA.COMMONS_VP.AR_INTERNAL_METADATA (
	KEY VARCHAR(16777216) NOT NULL,
	VALUE VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9) NOT NULL,
	UPDATED_AT TIMESTAMP_NTZ(9) NOT NULL,
	_ETL_BATCH_ID VARCHAR(16777216),
	_ETL_INSERT_DATE_TIME TIMESTAMP_NTZ(9),
	_ETL_UPDATE_DATE_TIME TIMESTAMP_NTZ(9)
);
