name: github_to_snowflake_deploy

# Controls when the action will run. 
on:
  push:
    branches:
      - develop
    paths:
      - 'github_to_s3_repo/**'
      - 'snowflake_db/**'

env:
  GITHUB_REF: "main"

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest
    environment: test_env
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          
          echo $CODE_REPO_DB_INDIA
          echo $RAW_DB_INDIA
          echo $STG_DB_INDIA
          echo $CURATED_DB_INDIA
          
          echo "Step 1: Replacing CODE_REPO Database names"
          find $GITHUB_WORKSPACE -name '*.sql' -exec sed -i 's/CODE_REPO_DB_INDIA/${{ env.CODE_REPO_DB_INDIA }}/g' {} +
          
          echo "Step 2: Replacing RAW Database names"
          find $GITHUB_WORKSPACE -name '*.sql' -exec sed -i 's/RAW_DB_INDIA/${{ env.RAW_DB_INDIA }}/g' {} +
          
          echo "Step 3: Replacing STG Database names"
          find $GITHUB_WORKSPACE -name '*.sql' -exec sed -i 's/STG_DB_INDIA/${{ env.STG_DB_INDIA }}/g' {} +
          
          echo "Step 4: Replacing CURATED Database names"
          find $GITHUB_WORKSPACE -name '*.sql' -exec sed -i 's/CURATED_DB_INDIA/${{ env.CURATED_DB_INDIA }}/g' {} +
          
          echo "Step 5: Installing schemachange"
          pip install schemachange
          
          echo "Step 6: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/snowflake_db -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table --vars '{"sf_database":"TEST_DB"}'
