name: github_to_snowflake_deploy

# Controls when the action will run. 
on:
  push:
    branches:
      - develop
    paths:
      - 'github_to_s3_repo/**'
      - 'snowflake_db/**'

env:
  GITHUB_REF: "main"

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest
    environment: test_env
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run schemachange
        env:
          SF_ACCOUNT: mr22578.ap-south-1
          SF_USERNAME: hrushikesh47blz
          SF_ROLE: ACCOUNTADMIN
          SF_WAREHOUSE: COMPUTE_WH
          SF_DATABASE: TEST_DB
          SNOWFLAKE_PASSWORD: Snowflake@12345!
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/snowflake_db -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table --vars '{"sf_database":"TEST_DB"}'
