name: python_github_to_s3_workflow

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'python_reports/**'

env:
  BUCKET_NAME : "my-github-bucket"
  AWS_REGION : "us-east-2"
  GITHUB_REF: "main"

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::160142254471:role/github_s3_role
        aws-region: us-east-2

    - name: Creating zip file
      run: |
       pwd
       mkdir -p /home/runner/work/github_to_s3_repo/github_to_s3_repo/python_reports
       mkdir -p /home/runner/work/github_to_s3_repo/github_to_s3_repo/python_reports/zip_output_files
       mkdir -p /home/runner/work/github_to_s3_repo/github_to_s3_repo/python_reports/zip_output_files/daily_metrics_report
       cd /home/runner/work/github_to_s3_repo/github_to_s3_repo/python_reports/zip_output_files/daily_metrics_report       
       zip daily_metrics_report.zip /home/runner/work/github_to_s3_repo/github_to_s3_repo/daily_metrics_report/scripts
      
    - name: Uploading to S3  
      run: |
        aws s3 sync ./python_reports/zip_output_files/ s3://my-github-bucket/python_reports/zip_output_files/
